 -- Tables
CREATE TABLE Event (
	eventId 	LONGINT AUTO_INCREMENT PRIMARY KEY,
	startTime 	TIMESTAMP NOT NULL,
	endTime 	TIMESTAMP NOT NULL,
	title		VARCHAR(100) NOT NULL,
	content		VARCHAR(500),
	locationId	INT NOT NULL,
	category	ENUM('HOSTEL', 'ACADEMIC', 'SPORTS', 'CULTURAL', 'TECHNICAL', 'ALCHER', 'TECHNICHE') NOT NULL,
	postedBy	VARCHAR(40) NOT NULL,	
	status		ENUM('ONGOING', 'SCHEDULED', 'CANCELLED', 'COMPLETED') NOT NULL,
	FOREIGN KEY(postedBy) REFERENCES Login(loginId),
	FOREIGN KEY(locationId) REFERENCES Location(locationId)
);

CREATE TABLE Location (
	locationId	INT AUTO_INCREMENT PRIMARY KEY,
	mainLand	ENUM('SAC','LT', 'MCOM', 'NAC', 'HOSTEL') NOT NULL,
	subLand		VARCHAR(40)
);

CREATE TABLE Login (
	loginId		VARCHAR(40) PRIMARY KEY,
	passwd		VARCHAR(40) NOT NULL,
	post		VARCHAR(40) NOT NULL
);

CREATE TABLE Remainder (
	time		TIMESTAMP NOT NULL,
	eventId		LONGINT,
	FOREIGN KEY (eventId) REFERENCES Event(eventId)
);


