INSERT INTO MainLand(mapId,mainLand) VALUES ("","Other");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_cc","Computer Center");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_library","Library");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_audi_circle",  "Auditorium Circle");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_kameng","Kameng Hostel");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_barak","Barak Hostel");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_lt","Lecture Theaters");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_a_lake","Lake in front of Academic complex");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_auditorium",	"Auditorium");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_umiam","Umiam Hostel");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_manas","Manas Hostel");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_dihing","Dihing Hostel");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_dibang","Dibang Hostel");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_kapili","Kapili Hostel");			
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_siang","Siang Hostel");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_brahmaputra","Brahmmaputra Hostel");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_kv","Kendriya Vidyalaya");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_CE","Department of Civil Engineering");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_BT","Department of Biotechnology");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_CH","Department of Chemistry");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_EEE","Department of Electronics and Electrical Engineering");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_CSE","Department of Computer Science and Engineering");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_CMMC_C1","Center for Educational Technology and Center for Mass Media Communication");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_DD","Department of Design");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_AC_PLANT","AC Plant");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_ME","Department of Mechanical Engineering");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_MA","Department of Mathematics");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_HSS","Department of Humanities & Social Studies");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_C4","Center for the Environment");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_CIF","Central Instruments Facility");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_C2_C3","Centre for Nano Technology & Centre for Energy");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_CL","Department of Chemical Engineering");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_PH","Department of Physics");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_workshop","Mechanical Workshop");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_conference_hall","Conference Hall");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_subansiri","Subansiri Hostel");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_indoor_gym","SAC Indore Gym");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_tennis","SAC Tennis Court");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_hockey","SAC Hockey Ground");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_football","SAC Football Ground");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_volley","SAC Volleyball Ground");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_basket","SAC Basketball Court");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_athletic","SAC Athletics Ground");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_cricket","SAC Cricket Ground");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_married","Married Scholars Hostel");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_power_house","Power House");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_swimming","Swimming Pool");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_tcs","Technology Complex");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_akshara","Akshara Pre Primary School");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_guest_house","Guest House");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_hospital","Hospital");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_community_hall","Community Hall");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_fac_B_1","Faculty B type Quarters");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_fac_C","Faculty C type Quarters");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_fac_D_1","Faculty D type Quarters 1");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_fac_D_2","Faculty D type Quarters 2");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_fac_D_3","Faculty D type Quarters 3");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_fac_E_1","Faculty E type Quarters 1");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_fac_E_2","Faculty E type Quarters 2");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_fac_F_1","Faculty F type Quarters 1");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_fac_F_2","Faculty F type Quarters 2");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_fac_F_3","Faculty F type Quarters 3");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_fac_F_4","Faculty F type Quarters 4");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_fac_F_5","Faculty F type Quarters 5");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_fac_comm_hall","Faculty Community Hall");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_admin","Administrative Building");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_bank","Banks & ATM");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_main_gate","Main Gate");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_market","Market Complex");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_dbunglow","Director Bunglow");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_aseb_gate","ASEB Gate");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_water_plant","Water Treatment Plant");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_serpentine_lake","Serpentine Lake");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_iitg_lake","IITG Lake");
INSERT INTO MainLand(mapId,mainLand) VALUES ("loc_guesthouse_lake","Lake in front of Guest House");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_tc_back","TC back road");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_tc_front","TC front road");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_hospi_road","Hospital road");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_sac_kapili","Road from SAC to Kapili");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_market","Junction near market complex");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_kameng_tc","Road between Kameng & TC");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_sac_audi","Road between SAC & Auditorium");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_core2","Core 2");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_core3","Core 3");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_ghouse","Surroundings of Guest House");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_kv_gate","KV Gate Road");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_core1","Core 1");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_core4","Core 4");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_viewpoint",	"View Point");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_faculty_gate","Faculty Gate");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_river","Brahmaputra River view");
INSERT INTO MainLand(mapId,mainLand) VALUES ("rsign_admin_circle","Circle near administrative building");
